### ISSUE TITLE
New PDF-Icon too wide

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#19]
It looks to me like the width of the new status item is wider then the other items.

![screen shot 2013-04-30 at 17 09 07](https://f.cloud.github.com/assets/333270/444617/ff3ce618-b1a7-11e2-8887-005e00a04a58.png)

The space between it and the round icon right of it is larger than the space between other items.

**Comment by JanX2** [comment]
Very odd. It looks perfectly fine here! And the numbers agree: the apple icons have, on average, 13 px white space on each side. This varies between 12 px and 15 px. We have 13 px. We could chop of one pixel on each side.

![autoingest too wide 2](https://f.cloud.github.com/assets/192294/444961/3585976c-b1b0-11e2-9cea-3264954c67ab.png)

On second thought this may be due to the F.lux icon having too wide a margin!

After living with the current state of affairs for a few hours, I believe that I should try and change the depth of the icon so that it appears less like a black hole and more like a shallower engraving.

**Comment by odrobnik** [comment]
Can you try that an check how this looks on your machine? I'm thinking since the apple is basically a circle it should touch the outsides if there is an additional space added by the system.

When I have an icon left of it as well it is also slightly too far.

Are you checking Retina or normal resolution? I am on normal.

**Comment by ricobeck** [comment]
![screen shot 2013-04-30 at 8 52 07 pm](https://f.cloud.github.com/assets/155457/445873/2dbe1182-b1c7-11e2-851c-98c3d791346e.png)
for me it looks good. (non-retina)

**Comment by odrobnik** [comment]
@ricobeck in your screenshot it looks like there is more space on the right

**Comment by JanX2** [comment]
That’s an effect of how humans perceive things. It’s the reason why we need to apply kerning to certain pairs of characters in typography ([Kerning](http://en.wikipedia.org/wiki/Kerning)).

**Comment by odrobnik** [comment]
So will we try with less space on the sides, or does everybody agree to leave it as it is now?

**Comment by JanX2** [comment]
I will tinker with it.

**Comment by JanX2** [comment]
OK. I am done tinkering and these are the results:

![autoingest too wide 3](https://f.cloud.github.com/assets/192294/454770/9022d60e-b33f-11e2-8c10-9e922875be47.png)
This is too narrow in my opinion. The icon get’s too cozy with the Skype icon.

![autoingest too wide 4](https://f.cloud.github.com/assets/192294/454771/914dcc82-b33f-11e2-8e85-9bb9caf5cfc3.png)
I will go with this version. I have lowered the contrast a teensy-weensy bit on this one so that it will better fit the rest. BTW: most of the Apple icons differ in their grayscale value: the larger the are the icon covers, the brighter it’s color.

The issue here really seems to be with the F.lux icon and not with ours. :)

Another aside: if someone ever want’s to tinker with this again, you will have to replace

```
    NSStatusItem *statusItem = [systemStatusBar statusItemWithLength:NSSquareStatusItemLength];
```

with

```
    NSStatusItem *statusItem = [systemStatusBar statusItemWithLength:NSVariableStatusItemLength];
```

I have yet to push this contrast change.

**Comment by JanX2** [comment]
OK. The second version now resides in c3ea8dfeb5156aab82227b8dc22a657839442906 (janx2/menu-improvements).

**Comment by odrobnik** [comment]
Is the image centered? It looks to be more to the left...

**Comment by JanX2** [comment]
It’s the F.lux icon playing tricks on you. :)

**Comment by halo** [comment]
> Another aside: if someone ever want’s to tinker with this again, you will have to replace

@JanX2 You just saved me (probably) hours of googling :)

**Comment by JanX2** [comment]
@halo Always glad to be of service. :)
