### ISSUE TITLE
Handle missing Download Folder

### ISSUE THREAD

**Issue by fcy** [Cocoanetics/AutoIngest#29]
I haven't tested what happens to the organizer (or the app) when the Download Folder doesn't exists. What should we do?

The organizer can silently ignore this and disable itself until a existing folder is set. What about the downloader does it already handle it?

**Comment by odrobnik** [comment]
See -canSynch in the report manager. It does not allow synching.

Organizing should do something similar. Not disable, but just not do anything until the parameters are valid

**Comment by odrobnik** [comment]
@fcy I would expect for -startMonitoring to check if _downloadFolder exists and bail out if it doesn't, possibly logging that folder watching could not be started because the folder did not exist.

**Comment by odrobnik** [comment]
I reclassified this as a bug since is not something that the user would notice, but that's a simple addition to prevent a potential problem. "defensive coding".

**Comment by odrobnik** [comment]
fixed in 493d56f0ff49102f2817bbbeb42d26258f29246d

**Comment by odrobnik** [comment]
Note: The FSEventStreamCreate does not care whether or not the folder exists. This safety check is also necessary because the user is able to type into the folder text box and potentially there will be multiple different paths for which the watcher will be called that don't exist. With this check added it will only start to watch folders that exist.
