### ISSUE TITLE
Organize Reports Into Folders

### ISSUE THREAD

**Issue by fcy** [Cocoanetics/AutoIngest#6]
The original suggestion is to make this hierarchy: `Vendor_ID/ReportType/ReportSubType/ReportDateType`

I think a simpler and "always on" approach is better. Simpler because we could use only two levels of folders `AppleID/VendorID` because the report types, subtypes and date is already in the file name. In this case even only the `VendorID` would work.

Basically we've two options:
1. Completely customizable folder structure per account (when the support is added)
2. Not customizable folder structure

What do you thing?

**Comment by fcy** [comment]
Also. I'll assign myself to this issue just to let everybody know what I'm going to do so that we don't waste time making the same thing another one is already doing.

**Comment by odrobnik** [comment]
There is the organization based on the credentials and on the logical hierarchy.
- what combination of login and vendor_id do you need to get to certain reports?
- what is the logical structure `Vendor_ID/ReportType/ReportSubType/ReportDateType`

Different ITC logins can allow access to the same Vendor_ID which is why I am advocating the latter structure.

We wouldn't really need one, but I think if somebody would like to have some structure it might be better to at least divide them by Vendor_ID. You have multiple vendor_IDs if you belong to multiple teams or if you - like me - first had an Individual account and switched to a company account.

The second motivation would be to reduce the number of files in a given folder to make importing faster and avoid running out of vnodes. i.e. I think the number of files in a folder is limited.

Third motivation was to do it similar like iTunes does if you choose to let it organize your music.

By itself the reports are unique, in summary having an organizing process would serve the need of some people to have at least some organization and possibly speed up importing with DTReportCore.

e.g. 81234567/Sales/Summary/Daily/S_D_81234567_20130101.txt.gz

**Comment by fcy** [comment]
Makes sense. Let's go with the more complete folder structure.

About activating it. It should be optional if the user only have one account with one vendor_id, as soon as he adds another account/vendor_id this auto organize feature should be always enable to avoid conflicts between them.

**Comment by odrobnik** [comment]
There are no conflicts possible since the names are unique.

I think we want the path for the output to be an internal method of the manager singleton and download new files either into the root of the reportFolder or into the correct place of the structure.

if the user switches between structure or not there should be a process kicked off in the background that moves existing folder into the structure. This way if you have them not organized and enable the structure it would move the files. I am unsure if it makes sense to move them back to the root folder if you unselect, maybe we want to ask the user:

Would you like to move files contained in the structure back to the root of your download folder? YES/NO

**Comment by fcy** [comment]
Whoa! I missed the vendor_id in the name.

I'll do it completely optional. When the users activates it the app organize the reports.

My initial idea to implement this is to make it works something like [Hazel](http://www.noodlesoft.com/hazel.php), the app listen to changes in the root folder and automatically moves the reports. This way the download is separate from the organization code.

**Comment by odrobnik** [comment]
Sounds like a great idea.

**Comment by odrobnik** [comment]
just be careful during downloading. At present the file gets written to the final location and then unzipped there. You probably want to write it to a temp location first if the user chose to unzip the reports.

**Comment by odrobnik** [comment]
Please always branch off the latest development HEAD if you create a new feature branch. Not master.

**Comment by fcy** [comment]
```
Please always branch off the latest development HEAD if you create a new feature branch. Not master.
```

I recreated the branch using develop as parent, just to make sure it wasn't branching off master. Although I'm not sure it was, nonetheless I also added support to OptIn as a new type to `ReportInformation`.

**Comment by odrobnik** [comment]
What is `ReportInformation`? The submodule already has the updated types.

**Comment by fcy** [comment]
It's a class to read the information of the reports based on its name. It uses the types defined in the submodules. It doesn't recreate anything (as far as I could find).

Take a look in the branch fcy/auto-organize-reports

**Comment by odrobnik** [comment]
@fcy I noticed you have your own implementation of converting the enums into strings. That duplicates the functions already in existence, please see: https://github.com/Cocoanetics/DTITCReportDownloader/blob/master/Core/Source/DTITCFunctions.h

**Comment by fcy** [comment]
Thanks for reviewing it. I'll change my implementation to use these functions.

**Comment by odrobnik** [comment]
@fcy I am merging the ongoing features branches into develop, what's your status here, can it be merged?

**Comment by fcy** [comment]
Not yet. I'll create a pull request when it's ready.

**Comment by odrobnik** [comment]
@fcy any chance of a pull request before Friday?

**Comment by fcy** [comment]
I don't think so. I'm taming the File System Events API but there still a bunch of details to look at, for example check if the report has already been downloaded in its organized-folder.

**Comment by fcy** [comment]
And I just thought something. On your blog there's this line:

> You can put this on each of your Macs if you download the reports to a shared Dropbox folder because each instance will automatically skip report files that are already present locally.

If the Auto Organize is enabled in only one Mac the skip-already-downloaded-reports won't work, because it would be checkin the wrong path.

**Comment by fcy** [comment]
Hi guys, the [`fcy/auto-organize-reports`](https://github.com/Cocoanetics/AutoIngest/tree/fcy/auto-organize-reports) is in its first working state. I think it would be nice if you check it out to see how it is currently working.

In my previous comment I expressed a problem that we need to figure out how to solve it.

**Comment by fcy** [comment]
Also a code review would be nice. I always appreciate feedback.

**Comment by odrobnik** [comment]
I don't think that this is an issue. With organisation on duplicate reports would be checked in the structure, without organisation they would checked against the download folder. If the user enables organisation on one machine he schould also enable it on the other.

Since there are only two places where a downloaded report can be it would be no problem to look for a file in both the download folder root and inside the organized structure.

**Comment by odrobnik** [comment]
@fcy I reviewed your code and I'm happy with it. I just did some adjustments to my coding style as you can see from my commits in the od/issue_6_cleanup branch.

I also added a warning if there is a report file in the report folder and it cannot be moved into the organized structure because a file of the same name already exists there.
